services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-node:v1
    container_name: api
    ports:
      - '${SERVER_PORT:-3000}:${SERVER_PORT:-3000}'
    environment:
      SERVER_PORT: ${SERVER_PORT:-3000}
      MONGODB_USER: ${MONGODB_USER:-root}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD:-123}
      MONGODB_HOST: mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-123}
    volumes:
      - database:/data/db

volumes:
  database:
