services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-node:v1
    container_name: api
    ports:
      - '${PORT}:${PORT}'
    environment:
      PORT: ${PORT}
      MONGODB_URL: ${MONGODB_URL}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - '${MONGODB_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - database:/data/db

volumes:
  database:
